---
permalink: migrate/migrate-to-latest-ontaptools.html
sidebar: sidebar
keywords: migrate
summary: 'When migrating storage data, storage backends are onboarded manually using REST APIs. When migrating VASA Provider data, data is exported from existing Derby database and imported into the MongoDB database.'
---
= Migrate from ONTAP tools for VMware vSphere 9.xx to 10.4
:icons: font
:imagesdir: ../media/

[.lead]
Moving the NetApp ONTAP tools for VMware vSphere setup from version 9.xx to 10.x necessitates a migration process because of the significant product updates and enhancements across the versions. 

You can migrate from ONTAP tools for VMware vSphere 9.12D1, 9.13D2, and 9.13P2 releases to ONTAP tools for VMware vSphere 10.4. 

//updated for OTVDOC-175 - jani

If you have NFS and VMFS datastores and no vVols datastores in your setup, simply uninstall ONTAP tools 9.xx and deploy ONTAP tools 10.x. However, if your setup contains vVols datastores, you’ll have to go through a process of migrating the VASA Provider and the SRA.  

The following table outlines the migration process in these two different scenarios. 
|===
|*If the setup has vVols datastores* |*If the setup contains only NFS and VMFS datastores*

|
Steps:

1. link:../migrate/sra-vasa-migration.html[Migrate the VASA Provider] 

2. https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html[Create VM storage policies]

|
Steps:

1. Remove ONTAP tools 9.xx from your environment. Refer to https://kb.netapp.com/data-mgmt/OTV/VSC_Kbs/OTV_How_to_remove_OTV_9_12_from_your_environment[How to remove OTV 9.xx from your environment] NetApp Knowledge Base article.

2. link:../deploy/quick-start.html[Deploy and configure ONTAP tools for VMware vSphere 10.4] 

3. link:../migrate/sra-vasa-migration.html[Update the SRA]

4. https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/storage-policy-based-management-in-vsphere/creating-and-managing-vsphere-storage-policies.html[Create VM storage policies]

|===
[NOTE]
After migrating from ONTAP tools for VMware vSphere 9.xx to 10.4, vVols datastores using the NVMe/FC protocol become non-operational because ONTAP tools 10.4 supports the NVMe-oF protocol only with VMFS datastores.

//updated for 10.3 jira OTVDOC-147
