---
permalink: protect/configure-placeholder-datastores.html
sidebar: sidebar
keywords:
summary: 'You should configure a placeholder datastore to hold a place in the vCenter inventory at the recovery site for the protected virtual machine \(VM\). The placeholder datastore does not need to be large because the placeholder VMs are small and use only a few hundred or fewer kilobytes.'
---
= Configure placeholder datastores
:icons: font
:imagesdir: ../media/

[.lead]
You should configure a placeholder datastore to hold a place in the vCenter inventory at the recovery site for the protected virtual machine (VM). The placeholder datastore does not need to be large because the placeholder VMs are small and use only a few hundred or fewer kilobytes.

.Before you begin

* You should have connected the protected and recovery sites.
* You should have configured your resource mappings.

.Steps

. Log in to vCenter Server and select *Site Recovery* > *Sites*.
. Select your protected site and select *Manage*.
. Select *Placeholder Datastores* > *New* in the manage tab to create a new placeholder datastore.
. Select the appropriate datastore and select *OK*.
+
NOTE: Placeholder datastores can be local or remote and should not be replicated.
. Repeat steps 3 to 5 to configure a placeholder datastore for the recovery site.
