---
permalink: protect/map-resource.html
sidebar: sidebar
keywords:
summary: 'You should map your resources on the protected site and recovery site so that virtual machines are configured to fail over into one group of hosts or the other.'
---
= Configure resource mappings
:icons: font
:imagesdir: ../media/

[.lead]
You should map your resources on the protected site and recovery site so that virtual machines are configured to fail over into one group of hosts or the other.

.Before you begin

You should have connected the protected and recovery sites.

NOTE: In VMware Live Site Recovery, resources can be resource pools, ESXi hosts, or vSphere clusters.

.Steps

. Log in to vCenter Server and select *Site Recovery* > *Sites*.
. Select your protected site and select *Manage*.
. Select *Resource Mappings* > *New* in the manage tab to create a new resource mapping.
. In the Create Resource Mapping wizard, perform the following:
 .. Select *Automatically Prepare Mappings for Resource with Matching Names* and select *Next*.
 .. Select the required data center objects for the protected and recovery sites and select *Add Mappings*.
 .. Select *Next* after mappings are created successfully.
 .. Select the object used earlier to create reverse mapping and then select *Finish*.

.Result

The Resource Mappings page displays the protected site resources and the recovery site resources. You can follow the same steps for other networks in your environment.
