---
permalink: manage/edit-esxi-host-settings.html
sidebar: sidebar
keywords:
summary: 'You can use the dashboard of ONTAP tools for VMware vSphere to edit your ESXi host settings.'
---
= Modify ESXi host settings using ONTAP tools
:icons: font
:imagesdir: ../media/

[.lead]
You can use the dashboard of ONTAP tools for VMware vSphere to edit your ESXi host settings.

.Before you begin

If there is an issue with your ESXi host settings, the issue is displayed in the ESXi host systems portlet of the dashboard. You can select the issue to view the host name or the IP address of the ESXi host that has the issue.

.Steps

. Log in to the vSphere client.
. In the shortcuts page, select *NetApp ONTAP tools* under the plug-ins section.
. Go to *ESXi Host compliance* portlet in the Overview (dashboard) of the ONTAP tools for VMware vSphere plug-in.
. Select *Apply Recommended Settings* link.
. In the *Apply recommended host settings* window, select the hosts that you want to comply with NetApp recommended host settings and select *Next*.
[NOTE]
You can expand the ESXi host to see the current values.
. In the settings page, select the recommended values as required.
. In the summary pane, check the values and select *Finish*.
You can track the progress in the recent task panel.

.Related information

link:../configure/configure-esx-server-multipath-and-timeout-settings.html[Configure ESXi host settings]
// updated for https://github.com/NetAppDocs/ontap-tools-vmware-vsphere-10/issues/45 - jani
